apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
type: Opaque
stringData:
  N8N_ENCRYPTION_KEY: {{ .Values.secrets.n8nEncryptionKey }}
  N8N_RUNNERS_AUTH_TOKEN: {{ .Values.secrets.n8nRunnersAuthToken }}
  DB_POSTGRESDB_PASSWORD: {{ .Values.secrets.dbPostgresPassword }}